http_addr: :9090
rpc_addr: :19090
log_path: ./gostd.log
redis:
database:
  student:
    dsn: "postgres://127.0.0.1:5432/student?sslmode=disable"
    driver_name: "postgres"
  teacher:
    dsn: "postgres://127.0.0.1:5432/teacher?sslmode=disable"
    driver_name: "postgres"
